"""
conftest.py — Shared fixtures for all tests.
"""
import os
import json
import pytest

# Set test environment variables BEFORE importing src modules
os.environ["AWS_DEFAULT_REGION"] = "us-east-1"
os.environ["AWS_ACCESS_KEY_ID"] = "testing"
os.environ["AWS_SECRET_ACCESS_KEY"] = "testing"
os.environ["REPORTS_TABLE"] = "test-reports"
os.environ["AUDIT_TABLE"] = "test-audit-logs"
os.environ["STATS_TABLE"] = "test-stats"
os.environ["SQS_QUEUE_URL"] = "https://sqs.us-east-1.amazonaws.com/000000000000/test-queue"
os.environ["EVENT_BUS_NAME"] = "test-event-bus"
os.environ["GEMINI_API_KEY"] = "test-key"
os.environ["LOG_LEVEL"] = "DEBUG"


@pytest.fixture
def sample_ingest_payload():
    """Valid POST /reports payload."""
    return {
        "reporter_source": "TWITTER",
        "reporter_id": "@somchai_123",
        "raw_content": "ไฟไหม้ร้านทอง เยาวราช ตอนนี้เลย!",
        "media_urls": ["https://img.host/fire123.jpg"],
        "geo_location": {"lat": 13.7411, "lon": 100.5104},
        "timestamp": "2026-02-18T14:30:00Z",
    }


@pytest.fixture
def sample_verify_payload():
    """Valid PATCH /reports/{id} payload."""
    return {
        "validation_status": "VERIFIED",
        "reviewer_id": "officer_007",
        "reviewer_notes": "Confirmed via CCTV feed.",
        "link_to_incident_id": None,
    }


@pytest.fixture
def sample_delete_payload():
    """Valid DELETE /reports/{id} payload."""
    return {
        "reason": "Contains sensitive PII data",
        "deleted_by": "admin_001",
    }


@pytest.fixture
def sample_sqs_message():
    """SQS message body as generated by ingest_handler."""
    return {
        "report_id": "r-test12345678",
        "reporter_source": "TWITTER",
        "reporter_id": "@somchai_123",
        "raw_content": "Fire near Central World! Smoke visible.",
        "media_urls": ["https://img.host/fire123.jpg"],
        "geo_location": {"lat": 13.7466, "lon": 100.5391},
        "timestamp": "2026-02-18T14:30:00Z",
        "source_external_id": "tweet_123456",
        "ingested_at": "2026-02-18T14:30:05Z",
    }


@pytest.fixture
def api_gateway_event():
    """Factory for API Gateway proxy integration events."""
    def _make(method="GET", path="/reports", body=None, path_params=None, query_params=None):
        event = {
            "httpMethod": method,
            "path": path,
            "resource": path,
            "pathParameters": path_params,
            "queryStringParameters": query_params,
            "headers": {
                "Content-Type": "application/json",
                "Authorization": "Bearer test-token",
            },
            "body": json.dumps(body) if body else None,
            "requestContext": {
                "requestId": "test-request-id",
            },
        }
        return event
    return _make


class MockContext:
    """Mock Lambda context object."""
    aws_request_id = "test-request-id-12345"
    function_name = "test-function"
    memory_limit_in_mb = 256
    invoked_function_arn = "arn:aws:lambda:us-east-1:000000000000:function:test"


@pytest.fixture
def lambda_context():
    return MockContext()
