# ============================================================
# S3 — Media Storage (Uploaded evidence files)
# ============================================================
# Stores images/videos uploaded as evidence for disaster reports.
# Access via presigned URLs generated by the API.
#
# Flow:
#   1. Client calls POST /reports/upload-url → gets presigned PUT URL
#   2. Client uploads file directly to S3 via presigned URL
#   3. Client includes the S3 URL in POST /reports media_urls field
# ============================================================

resource "aws_s3_bucket" "media" {
  bucket        = "${local.prefix}-media-${local.account_id}"
  force_destroy = true

  tags = {
    Name = "${local.prefix}-media"
  }
}

# Block all public access — media accessed only via presigned URLs
resource "aws_s3_bucket_public_access_block" "media" {
  bucket = aws_s3_bucket.media.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# CORS — allow browser-based uploads from the dashboard
resource "aws_s3_bucket_cors_configuration" "media" {
  bucket = aws_s3_bucket.media.id

  cors_rule {
    allowed_headers = ["*"]
    allowed_methods = ["GET", "PUT", "POST"]
    allowed_origins = ["*"]
    expose_headers  = ["ETag"]
    max_age_seconds = 3600
  }
}

# Lifecycle — auto-delete old media after 90 days
resource "aws_s3_bucket_lifecycle_configuration" "media" {
  bucket = aws_s3_bucket.media.id

  rule {
    id     = "expire-old-media"
    status = "Enabled"

    expiration {
      days = 90
    }
  }
}
